; ============================================================
;  Wire Cutter & Stripper - PlatformIO Project
;  เปิดโฟลเดอร์นี้ใน VSCode + PlatformIO Extension
; ============================================================

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    adafruit/Adafruit GFX Library@^1.11.9
    madhephaestus/ESP32Servo@^1.1.1
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

upload_speed = 921600

; SPIFFS สำหรับเก็บ frontend (data/index.html)
; Upload: PlatformIO > Upload Filesystem Image
board_build.filesystem = spiffs
board_build.partitions = default.csv
